name: Astro Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.17
        uses: actions/setup-java@v1
        with:
          java-version: 1.17

      - name: Restore Maven Cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: restore

      - name: Build with Maven
        run: mvn -B package -T12 --file pom.xml

      - name: Save Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: save